class TTMThermalModelBSQ;
class TTMThermalModelBQ;

//int BSQConstrainSQ(TTMThermalModelBSQ *model);
//int BSQConstrainSQC(TTMThermalModelBSQ *model);
//int BSQConstrainSQCb(TTMThermalModelBSQ *model);
//int BSQConstrainBSQ(TTMThermalModelBSQ *model, double B, double S, double Q);
//int BSQConstrainQQ(TTMThermalModelBSQ *model, double Q);
//int BSQConstrainS(TTMThermalModelBSQ *model);
//int BSQConstrainQ(TTMThermalModelBSQ *model);
//int BSQConstrainSQEN(TTMThermalModelBSQ *model, double eovern);
//int BSQConstrainSQPercolation(TTMThermalModelBSQ *model);
//int BSQConstrainSPercolation(TTMThermalModelBSQ *model);
//int BSQConstrainSEN(TTMThermalModelBSQ *model, double eovern);
//int BSQConstrainSQST3(TTMThermalModelBSQ *model, double sovert3);
//int BSQConstrainSST3(TTMThermalModelBSQ *model, double sovert3);
int BQConstrainBDens(TTMThermalModelBQ *model, double nb);
int BQConstrainEN(TTMThermalModelBQ *model, double eovern);
int BQConstrainQ(TTMThermalModelBQ *model);
int BQConstrainQBDens(TTMThermalModelBQ *model, double nb);
int BQConstrainQEN(TTMThermalModelBQ *model, double eovern);
int BQConstrainQNetBDens(TTMThermalModelBQ *model, double nb);
int BQConstrainQPercolation(TTMThermalModelBQ *model);
int BQConstrainQST3(TTMThermalModelBQ *model, double SoverT3);
int BQConstrainST3(TTMThermalModelBQ *model, double SoverT3);
int BQConstrainQBDens(TTMThermalModelBQ *model, double nb);
//int BSQConstrainSBDens(TTMThermalModelBSQ *model, double nb);
//int BSQConstrainSQBDens(TTMThermalModelBSQ *model, double nb);
//int BSQConstrainSQNetBDens(TTMThermalModelBSQ *model, double nb);
