language: cpp
compiler: g++
sudo: required
dist: xenial

before_install:
  - #sudo add-apt-repository ppa:beineri/opt-qt593-trusty -y
  - sudo add-apt-repository ppa:beineri/opt-qt-5.10.0-xenial -y
  - sudo apt-get update

install:
  - sudo apt-get install libatlas-base-dev
  - sudo apt-get install libatlas3-base
  - sudo apt-get install libgsl0ldbl
  - sudo apt-get install gsl-bin libgsl0-dev 
  - sudo apt-get install qt510base
  - source /opt/qt510/bin/qt510-env.sh

script:
  - qmake CONFIG+=release PREFIX=/usr
  - make -j$(nproc)
  - make INSTALL_ROOT=appdir -j$(nproc) install ; find appdir/
  - wget -c -q "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage

after_success:
  - find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - # curl --upload-file ThermusQt*.AppImage https://transfer.sh/ThermusQt-git.$(git rev-parse --short HEAD)-x86_64.AppImage
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh ThermusQt*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
