language: cpp
compiler: g++
sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt593-trusty -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install libatlas-base-dev
  - sudo apt-get install libatlas3-base
  - sudo apt-get install libgsl0ldbl
  - sudo apt-get install gsl-bin libgsl0-dev 
  - sudo apt-get install qt59base qt59svg
  - source /opt/qt59/bin/qt59-env.sh

script:
  - /opt/qt59/bin/qmake PREFIX=/usr
  - make
  - # Generate AppImage
  - sudo apt-get -y install checkinstall
  - sudo checkinstall --pkgname=app --pkgversion="1" --pkgrelease="1" --backup=no --fstrans=no --default --deldoc
  - mkdir -p appdir/usr/bin ; cd appdir
  - dpkg -x ../app_1-1_amd64.deb . ; find .
  - mv ./usr/local/bin/* ./usr/bin/ # Why is this needed despite PREFIX=/usr? Bug?
  - cp ./usr/share/icons/hicolor/48x48/apps/ThermusQt.icns .
  - cp ./usr/share/applications/ThermusQt.desktop .
  - cd ..
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/* -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/* -appimage
  - curl --upload-file ./ThermusQt*.AppImage https://transfer.sh/ThermusQt-git.$(git rev-parse --short HEAD)-x86_64.AppImage
